// ********RoostGPT********
// Test generated by RoostGPT for test cart-react using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
// Import necessary tools and the rootReducer
import rootReducer from '../../../../frontend/src/redux/root-reducer';
import { createStore } from 'redux';

describe('Root Reducer Integration Tests', () => {
  let store = createStore(rootReducer);

  it('should return the initial state of products reducer', () => {
    expect(store.getState().products).toEqual({});
  });

  it('should handle state changes in the cart reducer', () => {
    const action = { type: 'ADD_TO_CART', payload: { id: 1, quantity: 2 } };
    store.dispatch(action);
    expect(store.getState().cart).toEqual({ 1: { id: 1, quantity: 2 } });
  });

  it('should maintain the user reducer state independently', () => {
    const userAction = { type: 'SET_CURRENT_USER', payload: { username: 'user1' } };
    store.dispatch(userAction);
    expect(store.getState().user).toEqual({ username: 'user1' });
    // Ensuring other reducers are not affected
    expect(store.getState().products).toEqual({});
    expect(store.getState().cart).toEqual({});
  });

  // Additional tests can be included to test different actions and edge cases.
});


