// ********RoostGPT********
// Test generated by RoostGPT for test cart-react using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import { createStore, applyMiddleware } from "redux";
import rootReducer from "../../../../frontend/src/redux/root-reducer";
import store from "../../../../frontend/src/redux/store";
import middlewares from "../../../../frontend/src/redux/middleware";

describe("Redux Store configuration", () => {
  test("should create a store with the root reducer and middleware", () => {
    const testStore = store;
    expect(testStore.getState()).toEqual(createStore(rootReducer, applyMiddleware(...middlewares)).getState());
  });

  test("should include redux-thunk middleware", () => {
    const appliedMiddlewares = middlewares.map(middleware => middleware.name);
    expect(appliedMiddlewares).toContain("thunkMiddleware");
  });

  test("should include redux-logger middleware", () => {
    const appliedMiddlewares = middlewares.map(middleware => middleware.name);
    expect(appliedMiddlewares).toContain("loggerMiddleware");
  });

  test("should integrate redux dev tools", () => {
    const isDevToolsInstalled = typeof window.__REDUX_DEVTOOLS_EXTENSION__ !== "undefined";
    expect(isDev3\n\`ToolsInstalled).toBeTruthy();
  });
});

