// ********RoostGPT********
// Test generated by RoostGPT for test cart-react using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { render, screen } from '@testing-library/react';
import Footer from '../../../../../frontend/src/components/footer/footer.component';

describe('Footer Component', () => {
  beforeEach(() => {
    render(<Footer />);
  });

  test('should render without crashing', () => {
    const footerElement = screen.getByRole('contentinfo');
    expect(footerElement).toBeInTheDocument();
  });

  test('should display the correct copyright text', () => {
    const copyrightText = screen.getByText(/Copyrights © 2020/);
    expect(copyrightText).toBeInTheDocument();
  });

  test('should contain a link pointing to the correct URL', () => {
    const expectedUrl = 'https://www.linkedin.com/in/ajay-meena1/';
    const linkElement = screen.getByRole('link');
    expect(linkElement).toHaveAttribute('href', expectedUrl);
  });

  test('should match the snapshot for the Footer component', () => {
    const footerElement = screen.getByRole('contentinfo');
    expect(footerElement).toMatchSnapshot();
  });

});

