// ********RoostGPT********
// Test generated by RoostGPT for test cart-react using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { render } from '@testing-library/react';
import CustomButton from '../../../../../frontend/src/components/custom-button/custom-button.component';

describe('CustomButton Component', () => {
    test('renders children correctly', () => {
        const { getByText } = render(<CustomButton>Click me!</CustomButton>);
        expect(getByText('Click me!')).toBeInTheDocument();
    });

    test('applies google-sign-in class when isGoogleSignIn prop is true', () => {
        const { container } = render(<CustomButton isGoogleSignIn>Click me!</CustomButton>);
        expect(container.firstChild).toHaveClass('google-sign-in');
    });

    test('applies inverted class when inverted prop is true', () => {
        const { container } = render(<CustomButton inverted>Click me!</CustomButton>);
        expect(container.firstChild).toHaveClass('inverted');
    });

    test('passes additional props to button element', () => {
        const { container } = render(<CustomButton type="submit">Submit</CustomButton>);
        expect(container.firstChild).toHaveAttribute('type', 'submit');
    });
});

