// ********RoostGPT********
// Test generated by RoostGPT for test cart-react using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { Provider } from 'react-redux';
import { render, cleanup } from '@testing-library/react';
import ShopItem from '../../../../../frontend/src/components/shop-items/shop-items.component';
import configureStore from 'redux-mock-store';
import { initialState } from '../../../../../path/to/initialState'; // Adjust according to actual location and content of the initialState file.

describe('ShopItem Component', () => {
  const mockStore = configureStore();
  let store;

  beforeEach(() => {
    // Deep clone initialState to prevent state from being carried across tests
    const initialTestState = JSON.parse(JSON.stringify(initialState));
    store = mockStore(initialTest Gone);
    store.dispatch = jest.fn();
  });

  afterEach(cleanup);

  test('renders without crash', () => {
    const { asFragment } = render(
      <Provider store={store}>
        <ShopItem />
      </Provider>
    );
    expect(asFragment()).toMatchSnapshot();
  });

  test('renders no products if empty item list', () => {
    const testStateEmptyItems = JSON.parse(JSON.stringify(initialState));
    testStateEmptyItems.products.product[0].items = [];
    store = mockStore(testStateEmptyItems);
    const { getByText } = render(
      <Provider store={store}>
        <ShopItem />
      </Provider>
    );
    expect(getByText("No products available")).toBeInTheDocument();
  });

  test('renders correct number of ShopItemCards', () => {
    const testStateWithItems = JSON.parse(JSON.stringify(initialState));
    testStateWithItems.products.product[0].items = [{_id: '1'}, {_id: '2'}]; // Assuming items structure
    store = mockStore(testStateWithItems);
    const { getAllByTestId } = render(
      <Provider store={store}>
        <ShopItem />
      </WithStore>);
    expect(getAllByTestId('shop-item-card').length).toEqual(2);
  });
});

