// ********RoostGPT********
// Test generated by RoostGPT for test cart-react using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { render, fireEvent, cleanup } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import DirectoryItem from '../../../../../../frontend/src/components/directory-item/directoryItem.component';

describe('DirectoryItem Component', () => {
  const mockHistoryPush = jest.fn();
  const item = {
    title: 'Test Title',
    imageUrl: 'url-to-image.jpg',
    linkUrl: 'test-route'
  };

  const props = {
    history: {
      push: mockHistoryPush
    },
    item
  };

  const renderComponent = () =>
    render(
      <MemoryRouter>
        <DirectoryItem {...props} />
      </MemoryRouter>
    );

  afterEach(cleanup);

  test('renders correctly with given props', () => {
    const { getByText, getByTestId } = renderComponent();

    expect(getByText(item.title)).toBeInTheDocument();
    expect(getByTestId('image-background')).toHaveStyle(`backgroundImage: url(${item.imageUrl})`);
  });

  test('redirects to correct route on click', () => {
    const { getByText } = renderComponent();
    const titleElement = getByText(item.title);

    fireEvent.click(titleElement);

    expect(mockHistoryPush).toHaveBeenCalledWith(`/${item.linkUrl}`);
  });

  test('click on container redirects to the same route', () => {
    const { container } = renderComponent();
    const directoryItemContainer = container.firstChild;

    fireEvent.click(directoryItemContainer);

    expect(mockHistoryPush).toHaveBeenCalledTimes(2); // Because it's also called by the title element
  });
});

