// ********RoostGPT********
// Test generated by RoostGPT for test cart-react using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
// Import statements
import CartActionTypes from '../../../../../frontend/src/redux/cart/cart.types.js';

// Test suite
describe('CartActionTypes', () => {
    test('should have TOGGLE_CART_HIDDEN with correct value', () => {
        expect(CartActionTypes.TOGGLE_CART_HIDDEN).toBe('TOGGLE_CART_HIDDEN');
    });

    test('should have ADD_ITEM with correct value', () => {
        expect(CartActionTypes.ADD_ITEM).toBe('ADD_ITEM');
    });

    test('should have CLEAR_ITEM_FROM_CART with correct value', () => {
        expect(CartActionTypes.CLEAR_ITEM_FROM_CART).toBe('CLEAR_ITEM_FROM_CART');
    });

    test('should have REMOVE_ITEM with correct value', () => {
        expect(CartActionTypes.REMOVE_ITEM).toBe('REMOVE_ITEM');
    });
});


